version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./_storage/docs:/data/docs
    env_file:
      - .env
    restart: unless-stopped
